export const COMMON_QUESTIONS = [
  { id: 1, category: 'Mutations', question: 'What mutations were detected in this sequence?' },
  { id: 2, category: 'Mutations', question: 'Describe the insertion at position 1502.' },
  { id: 3, category: 'Mutations', question: 'Is the detected mutation pathogenic or benign?' },
  { id: 4, category: 'Mutations', question: 'What is the functional impact of the SNP at position 15?' },
  { id: 5, category: 'Mutations', question: 'Explain the frameshift caused by the insertion at locus 8.' },
  { id: 6, category: 'Mutations', question: 'What is a synonymous vs missense mutation?' },
  { id: 7, category: 'Mutations', question: 'How does a nonsense mutation affect protein synthesis?' },
  { id: 8, category: 'Mutations', question: 'What is the HGVS nomenclature for the detected variant?' },
  { id: 9, category: 'Mutations', question: 'Are there any hypermutable CpG sites in this sequence?' },
  { id: 10, category: 'Mutations', question: 'What is the mutation rate for this genomic region?' },
  { id: 11, category: 'Mutations', question: 'Compare insertion vs deletion impact on reading frame.' },
  { id: 12, category: 'Mutations', question: 'What codon change results from the C→T substitution?' },
  { id: 13, category: 'Mutations', question: 'Is the deletion at position 24 a stop-gain variant?' },
  { id: 14, category: 'Mutations', question: 'What clinical significance does ClinVar assign to similar variants?' },
  { id: 15, category: 'Mutations', question: 'How many total variants were found in this analysis?' },
  { id: 16, category: 'Mutations', question: 'What is the transition/transversion ratio (Ti/Tv)?' },
  { id: 17, category: 'Mutations', question: 'Explain the difference between germline and somatic mutations.' },
  { id: 18, category: 'Mutations', question: 'What is a copy number variant and was one detected?' },
  { id: 19, category: 'Mutations', question: 'How does a splice-site mutation differ from a missense mutation?' },
  { id: 20, category: 'Mutations', question: 'What is the predicted effect on protein structure?' },
  { id: 21, category: 'Quantum', question: 'How does the quantum SVM compare to classical Random Forest?' },
  { id: 22, category: 'Quantum', question: 'What is the statevector fidelity for the detected mutation?' },
  { id: 23, category: 'Quantum', question: 'Explain how nucleotide bases are encoded as qubit rotation angles.' },
  { id: 24, category: 'Quantum', question: 'What Ry gate angles correspond to A, T, G, and C?' },
  { id: 25, category: 'Quantum', question: 'How does CNOT entanglement help detect mutation patterns?' },
  { id: 26, category: 'Quantum', question: 'What is quantum coherence and how is it measured here?' },
  { id: 27, category: 'Quantum', question: 'Compare classical vs quantum confidence scores.' },
  { id: 28, category: 'Quantum', question: 'What is the Bloch sphere representation of this sequence?' },
  { id: 29, category: 'Quantum', question: 'How many qubits are used in the encoding circuit?' },
  { id: 30, category: 'Quantum', question: 'What is the quantum circuit depth for this analysis?' },
  { id: 31, category: 'Quantum', question: 'Explain Hadamard superposition in nucleotide encoding.' },
  { id: 32, category: 'Quantum', question: 'What is the phase shift (Δθ) for the critical deletion?' },
  { id: 33, category: 'Quantum', question: 'How does measurement collapse affect mutation detection?' },
  { id: 34, category: 'Quantum', question: 'What is quantum kernel estimation in genomic analysis?' },
  { id: 35, category: 'Quantum', question: 'Does the quantum model agree with the classical verdict?' },
  { id: 36, category: 'Quantum', question: 'What is the hybrid consensus score?' },
  { id: 37, category: 'Quantum', question: 'Explain ring CNOT topology in the 4-qubit circuit.' },
  { id: 38, category: 'Quantum', question: 'What noise model was applied to the simulation?' },
  { id: 39, category: 'Quantum', question: 'How does decoherence affect mutation call accuracy?' },
  { id: 40, category: 'Quantum', question: 'What is the advantage of quantum ML for variant calling?' },
  { id: 41, category: 'Sequence', question: 'What is the total sequence length analyzed?' },
  { id: 42, category: 'Sequence', question: 'What is the GC content of this sequence?' },
  { id: 43, category: 'Sequence', question: 'What is the AT content percentage?' },
  { id: 44, category: 'Sequence', question: 'How many adenine (A) bases are in the sequence?' },
  { id: 45, category: 'Sequence', question: 'How many guanine (G) bases are in the sequence?' },
  { id: 46, category: 'Sequence', question: 'What is the genomic stability score?' },
  { id: 47, category: 'Sequence', question: 'Describe the double-helix structure of this DNA.' },
  { id: 48, category: 'Sequence', question: 'What is the 5′ to 3′ direction of the analyzed strand?' },
  { id: 49, category: 'Sequence', question: 'Are there any low-complexity regions in the sequence?' },
  { id: 50, category: 'Sequence', question: 'What is the alignment identity percentage?' },
  { id: 51, category: 'Sequence', question: 'How many mismatches were found during alignment?' },
  { id: 52, category: 'Sequence', question: 'What reference genome was used for comparison?' },
  { id: 53, category: 'Sequence', question: 'Is this sequence from chromosome 22?' },
  { id: 54, category: 'Sequence', question: 'What is the file format of the input (FASTA/FASTQ)?' },
  { id: 55, category: 'Sequence', question: 'Are there repetitive elements in this region?' },
  { id: 56, category: 'Sequence', question: 'What is the melting temperature (Tm) of this sequence?' },
  { id: 57, category: 'Sequence', question: 'How many hydrogen bonds connect A-T vs G-C pairs?' },
  { id: 58, category: 'Sequence', question: 'What is the codon usage bias in this region?' },
  { id: 59, category: 'Sequence', question: 'Are there any palindromic sequences detected?' },
  { id: 60, category: 'Sequence', question: 'What is the Shannon entropy of this sequence?' },
  { id: 61, category: 'Motifs', question: 'What TATA box motifs were found?' },
  { id: 62, category: 'Motifs', question: 'How many GC box (Sp1 binding) sites are present?' },
  { id: 63, category: 'Motifs', question: 'What is a poly-A signal and where was it detected?' },
  { id: 64, category: 'Motifs', question: 'List all detected regulatory motifs in this sequence.' },
  { id: 65, category: 'Motifs', question: 'What is the significance of the CCGCCC motif?' },
  { id: 66, category: 'Motifs', question: 'Are there any transcription factor binding sites?' },
  { id: 67, category: 'Motifs', question: 'How many motif occurrences were found in total?' },
  { id: 68, category: 'Motifs', question: 'What positions contain the TATAAA promoter motif?' },
  { id: 69, category: 'Motifs', question: 'Explain the role of GC boxes in gene regulation.' },
  { id: 70, category: 'Motifs', question: 'Are there any CpG islands in this region?' },
  { id: 71, category: 'Clinical', question: 'What disease associations exist for these variants?' },
  { id: 72, category: 'Clinical', question: 'Is this variant associated with BRCA1-related cancer risk?' },
  { id: 73, category: 'Clinical', question: 'What is the ACMG classification for this mutation?' },
  { id: 74, category: 'Clinical', question: 'Should this variant be reported to the patient?' },
  { id: 75, category: 'Clinical', question: 'What is the allele frequency in gnomAD for similar variants?' },
  { id: 76, category: 'Clinical', question: 'Is this a known pharmacogenomic variant?' },
  { id: 77, category: 'Clinical', question: 'What is the zygosity of the detected variant?' },
  { id: 78, category: 'Clinical', question: 'Does this variant affect drug metabolism enzymes?' },
  { id: 79, category: 'Clinical', question: 'What is the penetrance of this mutation type?' },
  { id: 80, category: 'Clinical', question: 'Are there any actionable findings in this report?' },
  { id: 81, category: 'Analysis', question: 'Summarize the overall analysis results.' },
  { id: 82, category: 'Analysis', question: 'What is the AI confidence score for mutation detection?' },
  { id: 83, category: 'Analysis', question: 'What risk level was assigned to the detected mutation?' },
  { id: 84, category: 'Analysis', question: 'How long did this analysis take to complete?' },
  { id: 85, category: 'Analysis', question: 'What pipeline steps were executed?' },
  { id: 86, category: 'Analysis', question: 'Can you generate a research paper summary?' },
  { id: 87, category: 'Analysis', question: 'What is the consensus verdict between all methods?' },
  { id: 88, category: 'Analysis', question: 'How does this result compare to previous runs?' },
  { id: 89, category: 'Analysis', question: 'What quality control metrics were applied?' },
  { id: 90, category: 'Analysis', question: 'Explain the digital twin visualization modes.' },
  { id: 91, category: 'General', question: 'What is QuantumDNA X and how does it work?' },
  { id: 92, category: 'General', question: 'What is the difference between classical and quantum genomics?' },
  { id: 93, category: 'General', question: 'How do I interpret the 3D DNA digital twin?' },
  { id: 94, category: 'General', question: 'What file formats can I upload for analysis?' },
  { id: 95, category: 'General', question: 'What is a digital twin in genomics?' },
  { id: 96, category: 'General', question: 'How accurate is the AI mutation predictor?' },
  { id: 97, category: 'General', question: 'What is Qiskit and how is it used here?' },
  { id: 98, category: 'General', question: 'Can I export the analysis results as PDF?' },
  { id: 99, category: 'General', question: 'What sample datasets are available for demo?' },
  { id: 100, category: 'General', question: 'How do I navigate the mutation hotspot registry?' },
];

export const QUESTION_CATEGORIES = [...new Set(COMMON_QUESTIONS.map((q) => q.category))];
