export const SampleDatasets = {
  brca1: {
    id: "brca1",
    name: "BRCA1 Gene Variant (Exon 11 Fragment)",
    description: "Human BRCA1 gene fragment associated with hereditary breast and ovarian cancer risk analysis.",
    referenceSequence: "ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCAGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGG",
    candidateSequence: "ATGGATTTATCTGCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTACCATCTGTCTGGAGTTGATCAAGGAACCTGTCTCCACAAAGTGTGACCACATATTTTGCAAATTTTGCATGCTGAAACTTCTCAACCCGAAGAAAGGGCCTTCACAGTGTCCTTTATGTAAGAATGATATAACCAAAAGG",
    fileType: "FASTA",
    header: ">BRCA1_Human_Exon11_Mutant_Sample"
  },
  sarscov2: {
    id: "sarscov2",
    name: "SARS-CoV-2 Spike Protein Receptor Binding Domain",
    description: "Viral RNA sequence segment encoding the spike glycoprotein with key point mutations.",
    referenceSequence: "ATGTTTGTTTTTCTTGTTTTATTGCCACTAGTCTCTAGTCAGTGTGTTAATCTTACAACCAGAACTCAATTACCCCCTGCATACACTAATTCTTTCACACGTGGTGTTTATTACCCTGACAAAGTTTTCAGATCCTCAGTTTTACATTCAACTCAGGACTTGTTCTTACCTTTCTTTTCCAATGTTACTTGGTTCCATGCTATACATGTC",
    candidateSequence: "ATGTTTGTTTTTCTTGTTTTATTGCCACTAGTCTCTAGTCAGTGTGTTAATCTTACAACCAGAACTCAATTACACCCTGCATACACTAATTCTTTCACACGTGGTGTTTATTACCCTGATAAAGTTTTCAGATCCTCAGTTTTACATTCAACTCAGGACTTGTTCTTACCTTTCTTTTCCAATGTTACTTGGTTCCATGCTATACATGTC",
    fileType: "FASTA",
    header: ">SARS-CoV-2_Spike_RBD_Variant"
  },
  huntington: {
    id: "huntington",
    name: "Huntington HTT Gene CAG Trinucleotide Expansion",
    description: "Huntingtin gene exon 1 containing CAG trinucleotide repeat expansion motif associated with neurodegeneration.",
    referenceSequence: "ATGGCGACCCTGGAAAAGCTGATGAAGGCCTTCGAGTCCCTCAAGTCCTTCCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAACAGCAGCAGCAGCAGCAGCAACAGCAACAGCAGCAGCAACAGCAGCAGCAGCAGCAAGAGGAGGAGGAGGA",
    candidateSequence: "ATGGCGACCCTGGAAAAGCTGATGAAGGCCTTCGAGTCCCTCAAGTCCTTCCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAACAGCAGCAGCAGCAGCAAGAGGAGGAGGAGGA",
    fileType: "FASTA",
    header: ">HTT_Huntington_CAG_Expansion"
  },
  crispr: {
    id: "crispr",
    name: "CRISPR-Cas9 Off-Target Benchmark Site",
    description: "Target DNA sequence evaluated for potential CRISPR Cas9 guide RNA mismatch and off-target cleavage.",
    referenceSequence: "GCTGAACGGTAGCATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGACTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGC",
    candidateSequence: "GCTGAACGGTAGCATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGTCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGC",
    fileType: "TXT",
    header: ">CRISPR_Cas9_Target_Locus"
  }
};
